# EDA para toma de decissión
Aquí definiré la variable objetivo al entender la limpieza de mis datos, la distribución y multiples metricas estadisticas

## Datos

In [1]:
import json
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as datetime

In [2]:
ruta = "../data/Streaming_History_Audio_2026.json"

df = pd.read_json(ruta)
df.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2025-12-17T02:30:15Z,windows,238423,MX,2806:2f0:a7e1:fe5b:e80b:6db9:a0d7:912a,Jenga (Cuando Te Dejaba Ganar),Procrastinación 1 Yo 0,Caídas y Vueltas,spotify:track:5BLRVVXNBbOfepvtTBi75t,NaN,...,NaN,NaN,NaN,trackdone,logout,True,False,False,1765938376,0.0
1,2026-01-01T12:46:23Z,ios,82327,MX,189.203.193.241,Do Nothin' Till You Hear From Me - 1956 Version,Billie Holiday,Ben Webster's Finest Hour,spotify:track:1UJJ2S9LLjOdSRV5GcKsZe,NaN,...,NaN,NaN,NaN,trackdone,unexpected-exit-while-paused,False,False,False,1767221154,0.0
2,2026-01-02T18:24:41Z,windows,192467,MX,136.226.112.100,slow,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:4aaiI9YCt4KucUsMmLfGOx,NaN,...,NaN,NaN,NaN,fwdbtn,trackdone,False,False,False,1767378088,0.0
3,2026-01-02T18:28:18Z,windows,217573,MX,136.226.112.100,thorn,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:4JX851uapk8BbbZ6ZkNIHn,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,1767378279,0.0
4,2026-01-02T18:31:48Z,windows,210360,MX,136.226.112.100,cigarette in your bed,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:7cQcEUO7KLVciSS5LqzoyZ,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,1767378497,0.0

## Inspección estructural

In [3]:
df.shape

(10589, 23)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10589 entries, 0 to 10588
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ts                                 10589 non-null  object
 1   platform                           10589 non-null  object
 2   ms_played                          10589 non-null  int64
 3   conn_country                       10589 non-null  object
 4   ip_addr                            10589 non-null  object
 5   master_metadata_track_name         10589 non-null  object
 6   master_metadata_album_artist_name  10589 non-null  object
 7   master_metadata_album_album_name   10589 non-null  object
 8   spotify_track_uri                  10589 non-null  object
 9   episode_name                       0 non-null      float64
 10  episode_show_name                  0 non-null      float64
 11  spotify_episode_uri                0 non-null      float64
 12  audiobook_title                    0 non-null      float64
 13  audiobook_uri                      0 non-null      float64
 14  audiobook_chapter_uri              0 non-null      float64
 15  audiobook_chapter_title            0 non-null      float64
 16  reason_start                       10589 non-null  object
 17  reason_end                         10589 non-null  object
 18  shuffle                            10589 non-null  bool
 19  skipped                            10589 non-null  bool
 20  offline                            10589 non-null  bool
 21  offline_timestamp                  10589 non-null  int64
 22  incognito_mode                     10586 non-null  float64
dtypes: bool(3), float64(8), int64(2), object(10)
memory usage: 1.6+ MB

Al observar que 'ts' se encuentra en object se transforma a datetime para poder utilizarla

In [5]:
df['ts'] = pd.to_datetime(df['ts'])
print(df.dtypes)

ts                                   datetime64[ns, UTC]
platform                                          object
ms_played                                          int64
conn_country                                      object
ip_addr                                           object
master_metadata_track_name                        object
master_metadata_album_artist_name                 object
master_metadata_album_album_name                  object
spotify_track_uri                                 object
episode_name                                     float64
episode_show_name                                float64
spotify_episode_uri                              float64
audiobook_title                                  float64
audiobook_uri                                    float64
audiobook_chapter_uri                            float64
audiobook_chapter_title                          float64
reason_start                                      object
reason_end                                        object
shuffle                                             bool
skipped                                             bool
offline                                             bool
offline_timestamp                                  int64
incognito_mode                                   float64
dtype: object

se transforman los datos de ts a datos mas entendibles de día y hora

In [6]:
# convertimos de UTC a MX
df['ts'] = df['ts'].dt.tz_convert('America/Mexico_City')

df['day_of_week'] = df['ts'].dt.dayofweek 
df['hour'] = df['ts'].dt.hour

df[['ts', 'day_of_week', 'hour', 'skipped']].head()

                         ts  day_of_week  hour  skipped
0 2025-12-16 20:30:15-06:00            1    20    False
1 2026-01-01 06:46:23-06:00            3     6    False
2 2026-01-02 12:24:41-06:00            4    12    False
3 2026-01-02 12:28:18-06:00            4    12    False
4 2026-01-02 12:31:48-06:00            4    12    False

In [7]:
df.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode,day_of_week,hour
0,2025-12-16 20:30:15-06:00,windows,238423,MX,2806:2f0:a7e1:fe5b:e80b:6db9:a0d7:912a,Jenga (Cuando Te Dejaba Ganar),Procrastinación 1 Yo 0,Caídas y Vueltas,spotify:track:5BLRVVXNBbOfepvtTBi75t,NaN,...,NaN,trackdone,logout,True,False,False,1765938376,0.0,1,20
1,2026-01-01 06:46:23-06:00,ios,82327,MX,189.203.193.241,Do Nothin' Till You Hear From Me - 1956 Version,Billie Holiday,Ben Webster's Finest Hour,spotify:track:1UJJ2S9LLjOdSRV5GcKsZe,NaN,...,NaN,trackdone,unexpected-exit-while-paused,False,False,False,1767221154,0.0,3,6
2,2026-01-02 12:24:41-06:00,windows,192467,MX,136.226.112.100,slow,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:4aaiI9YCt4KucUsMmLfGOx,NaN,...,NaN,fwdbtn,trackdone,False,False,False,1767378088,0.0,4,12
3,2026-01-02 12:28:18-06:00,windows,217573,MX,136.226.112.100,thorn,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:4JX851uapk8BbbZ6ZkNIHn,NaN,...,NaN,trackdone,trackdone,False,False,False,1767378279,0.0,4,12
4,2026-01-02 12:31:48-06:00,windows,210360,MX,136.226.112.100,cigarette in your bed,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:7cQcEUO7KLVciSS5LqzoyZ,NaN,...,NaN,trackdone,trackdone,False,False,False,1767378497,0.0,4,12

In [8]:
df.isnull().sum()

ts                                       0
platform                                 0
ms_played                                0
conn_country                             0
ip_addr                                  0
master_metadata_track_name               0
master_metadata_album_artist_name        0
master_metadata_album_album_name         0
spotify_track_uri                        0
episode_name                         10589
episode_show_name                    10589
spotify_episode_uri                  10589
audiobook_title                      10589
audiobook_uri                        10589
audiobook_chapter_uri                10589
audiobook_chapter_title              10589
reason_start                             0
reason_end                               0
shuffle                                  0
skipped                                  0
offline                                  0
offline_timestamp                        0
incognito_mode                           3
day_of_week                              0
hour                                     0
dtype: int64

al observar variables con muchos nulos hacemos drop

In [9]:
columnas_null = [
    "episode_name", 
    "episode_show_name", 
    "spotify_episode_uri", 
    "audiobook_title", 
    "audiobook_uri", 
    "audiobook_chapter_uri", 
    "audiobook_chapter_title"
]

df = df.drop(columns=columnas_null)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10589 entries, 0 to 10588
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ts                                 10589 non-null  datetime64[ns, America/Mexico_City]
 1   platform                           10589 non-null  object
 2   ms_played                          10589 non-null  int64
 3   conn_country                       10589 non-null  object
 4   ip_addr                            10589 non-null  object
 5   master_metadata_track_name         10589 non-null  object
 6   master_metadata_album_artist_name  10589 non-null  object
 7   master_metadata_album_album_name   10589 non-null  object
 8   spotify_track_uri                  10589 non-null  object
 9   reason_start                       10589 non-null  object
 10  reason_end                         10589 non-null  object
 11  shuffle                            10589 non-null  bool
 12  skipped                            10589 non-null  bool
 13  offline                            10589 non-null  bool
 14  offline_timestamp                  10589 non-null  int64
 15  incognito_mode                     10586 non-null  float64
 16  day_of_week                        10589 non-null  int32
 17  hour                               10589 non-null  int32
dtypes: bool(3), datetime64[ns, America/Mexico_City](1), float64(1), int32(2), int64(2), object(9)
memory usage: 1.2+ MB

evaluate object values to see if we can do one-hot encoding to get more corr on variables

In [10]:
obj_cols = [
    "platform",
    "conn_country",
    "ip_addr",
    "master_metadata_track_name",
    "master_metadata_album_artist_name",
    "master_metadata_album_album_name",
    "spotify_track_uri",
    "reason_start",
    "reason_end"
]

valores_unicos_df = {}

for col in obj_cols:
    valores_unicos_df[col] = df[col].dropna().unique().tolist()
    print("\nValores unicos de ", col)
    print(valores_unicos_df[col])
    print("Cantidad de unicos: ", df[col].nunique())

Valores unicos de  platform
['windows', 'ios', 'osx', 'unknown']
Cantidad de unicos:  4

Valores unicos de  conn_country
['MX', 'US']
Cantidad de unicos:  2

Valores unicos de  ip_addr
['2806:2f0:a7e1:fe5b:e80b:6db9:a0d7:912a', '189.203.193.241', '136.226.112.100', '165.225.218.173', '2806:2f0:a7e1:fe5b:3cd7:85e4:6a01:90fc', '2806:2f0:a7e1:fe5b:c474:aa60:a167:653d', '2806:2f0:a7e1:fe5b:94e4:dcd9:805b:7cf2', '2806:2f0:a7e1:fe5b:5928:af52:f7c1:eb3a', '187.188.10.211', '2806:2f0:a7e1:fe5b:20b9:195b:828d:470c', '136.226.112.91', '2806:2f0:a7e1:fe5b:d020:9e2:58f7:7ab0', '148.244.203.162', '136.226.0.164', '170.85.66.205', '2806:2f0:a7e1:fe5b:81c:8d84:edad:7f35', '136.226.112.83', '136.226.0.194', '2806:2f0:a7e1:fe5b:643f:398a:af9f:2a5d', '2806:2f0:a7e1:fe5b:4544:47f9:5594:1da6', '148.244.203.166', '2806:2f0:a7e1:fe5b:3571:70a4:8517:7187', '2806:2f0:a7e1:fe5b:9120:e576:96e2:c425', '136.226.112.99', '136.226.0.199', '2806:2f0:a7e1:fe5b:3819:e7e8:ad19:a8af', '148.244.203.168', '148.244.203.165', '2806:2f0:a7e1:fe5b:d472:1c52:1510:f201', '2806:2f0:a7e1:fe5b:d5cf:ac8b:fe4:c49e', '2806:2f0:a7e1:fe5b:f809:6f0e:8b33:d92a', '200.68.183.174', '2806:2f0:a7e1:fe5b:ad7f:8ce8:2d88:361a', '201.124.116.41', '2806:2f0:a7e1:fe5b:48e5:188d:a7e6:1076', '2806:2f0:a7e1:fe5b:d5ed:3afb:bc52:98e2', '2806:2f0:a7e1:fe5b:cdbf:77ef:a10d:a7a8', '200.68.158.28', '2806:2f0:a7e1:fe5b:9d25:be10:6d9b:860a', '200.68.158.13', '136.226.112.169', '200.68.159.16', '2806:2f0:a7e1:fe5b:2cc7:7134:3eb5:a587', '2806:2f0:a7e1:fe5b:2d39:2dec:8d7b:8b0a', '2806:2f0:a7e1:fe5b:e92e:855e:d5db:a9aa', '2806:2f0:a7e1:fe5b:983c:3f54:f3d3:295c', '2806:2f0:a7e1:fe5b:883a:6dc6:1740:4433', '2806:2f0:a7e1:fe5b:fd21:a96:36de:f089', '2806:2f0:a7e1:fe5b:e564:a8d1:7876:28a6', '136.226.0.173', '148.244.203.167', '2806:2f0:a7e1:fe5b:3923:8170:37d9:3c79', '2806:2f0:a7e1:fe5b:49a2:8988:ecf6:251c', '148.241.64.30', '200.68.159.133', '2806:2f0:a7e1:fe5b:bc26:f32a:c8ef:e86f', '200.68.173.31', '200.68.159.191', '2806:2f0:a7e1:fe5b:9da3:c47e:27d5:e6a2', '2806:2f0:a7e1:fe5b:f0c0:57:6dfa:f9da', '2806:2f0:a7e1:fe5b:4090:a44:4bfb:6b4', '2806:2f0:a7e1:fe5b:91e0:c8ef:7834:a84b', '200.68.158.81', '200.68.159.21', '187.230.156.38', '2806:2f0:a7e1:fe5b:644e:3d70:6afa:b9ed', '200.68.158.85', '2806:2f0:a7e1:fe5b:4484:d9f1:2fe5:aa48', '136.226.0.176', '200.68.159.172', '136.226.0.202', '136.226.0.178', '2806:2f0:a7e1:fe5b:25c7:afef:9d59:74b9', '2806:2f0:a7e1:fe5b:9035:9097:e3d6:5aa3', '200.68.173.138', '148.244.203.169', '2806:2f0:a7e1:fe5b:1c21:b185:b599:372', '148.241.64.87', '2806:2f0:a7e1:fe5b:31ea:7933:b24a:a28f', '2806:2f0:a7e1:fe5b:ed92:fedb:c8d2:6758', '2806:2f0:a7e1:fe5b:6cd5:7a4c:efee:94be', '2806:2f0:a7e1:fe5b:282d:d763:80ad:60a0', '2806:2f0:a7e1:fe5b:bc5e:c038:8c0b:3ea8', '2806:2f0:a7e1:fe5b:957c:1269:b03a:b57e', '2806:2f0:a7e1:fe5b:69e1:f27b:cbca:398f', '2806:2f0:a7e1:fe5b:1c9:5aaf:1a9f:2d9b', '2806:2f0:a7e1:fe5b:6416:e94e:91a5:a5c8', '200.68.158.90', '148.241.64.57', '2806:2f0:a7e1:fe5b:f14b:1636:ffb0:861a', '2806:2f0:a7e1:fe5b:25ab:ecd9:fefe:ffdf', '136.226.112.208', '200.68.183.157', '200.68.183.28', '2806:2f0:a7e1:fe5b:69ce:343c:7d97:5d99', '2806:2f0:a7e1:fe5b:fdbc:1f6d:c852:9351', '2806:2f0:a7e1:fe5b:dc50:32a6:11bc:9962', '200.68.187.168', '187.170.40.16', '201.103.44.122', '187.170.10.109', '2806:2f0:a7e1:fe5b:94a8:67c3:6f56:24ab', '200.68.187.44', '200.68.187.99', '200.68.183.43', '148.241.64.36', '200.68.183.15', '136.226.112.209', '200.68.173.14', '200.68.173.62', '148.241.64.60', '2806:2f0:a7e1:fe5b:f069:302a:c2dd:92e5', '148.241.64.18', '2806:2f0:a7e1:fe5b:9413:a550:30e2:bdf2', '2806:2f0:a7e1:fe5b:99cf:d582:e5e0:ab0b', '2806:2f0:a7e1:fe5b:ec0d:9787:7c21:4f0e', '200.68.173.74', '2806:2f0:a7e1:fe5b:355d:53e2:5ec8:a206', '2806:2f0:a7e1:fe5b:70ba:ebbf:79a5:797e', '2806:2f0:a7e1:fe5b:8060:ca3a:854d:de2e', '2806:2f0:a7e1:fe5b:ad85:a285:da88:55a8', '2806:2f0:a7e1:fe5b:fccd:cc4c:eaae:d3f1', '148.241.64.15', '200.68.183.161', '2806:2f0:a7e1:fe5b:1987:9650:d0d8:2819', '2806:2f0:a7e1:fe5b:8064:bd2b:7c73:38bd', '148.241.64.66', '2806:2f0:a7e1:fe5b:280d:a65c:c262:a7dd', '200.68.173.18', '136.226.0.169', '200.68.173.179', '2806:2f0:a7e1:fe5b:48d2:4309:b17c:6230', '200.68.173.201', '136.226.0.184', '170.85.66.201', '136.226.0.167', '200.68.129.137', '148.241.64.21', '2806:2f0:a7e1:fe5b:80aa:38f6:7971:fa3f', '200.68.158.82', '200.68.158.45', '200.68.183.179', '200.68.173.245', '200.68.183.21', '2806:2f0:a7e1:fe5b:b920:6655:2a5f:735c', '187.189.214.214', '2806:2f0:a7e1:fe5b:75d6:70a4:bc71:9033', '200.68.183.14', '200.68.183.138', '2806:2f0:a7e1:fe5b:fcc3:4e84:8d2a:dd52', '136.226.112.197', '136.226.112.187', '187.191.39.153', '2806:2f0:a7e1:fe5b:5c04:7bfb:19c:b136', '200.68.183.151', '148.244.203.164', '136.226.112.121', '200.68.183.166', '148.241.64.90', '148.241.64.3', '2806:2f0:a7e1:fe5b:55ad:4338:6a4:ac6c', '2806:2f0:a7e1:fe5b:ddb3:a4dd:f876:762d', '2806:2f0:a7e1:fe5b:ace8:6ee9:ebb0:aec0', '2806:2f0:a7e1:fe5b:40b:1f7a:9ead:74a6', '187.189.221.238', '200.68.183.168', '2806:2f0:a7e1:fe5b:7904:2805:faa0:5ae', '136.226.112.97', '2806:2f0:a7e1:fe5b:31bb:e29a:410e:f796', '200.68.159.140', '200.68.183.76', '2806:2f0:a7e1:fe5b:ec70:b645:3d95:2e06', '2806:2f0:a7e1:fe5b:65f3:6269:51e1:64b3', '148.241.64.93', '2806:2f0:a7e1:fe5b:5de9:9489:3c2f:8af9', '200.68.159.33', '200.68.183.176', '2806:2f0:a7e1:fe5b:d972:aba9:7101:6363', '200.68.183.25', '2806:2f0:a7e1:fe5b:64ef:e72:21c8:90', '2806:2f0:a7e1:fe5b:1c99:4868:2c4e:9e91', '200.68.173.25', '2806:2f0:a7e1:fe5b:a5f2:bd9:8f5f:c92e', '200.68.173.41', '200.68.159.145', '2806:2f0:a7e1:fe5b:8e6:108c:756:bcb1', '2806:2f0:a7e1:fe5b:9482:e954:e242:de7a', '2806:2f0:a7e1:fe5b:a0c1:db73:641:9e54', '200.68.159.41', '2806:2f0:a7e1:fe5b:199e:4088:e862:6672', '200.68.173.189', '2806:2f0:a7e1:fe5b:94cf:c9b:480a:8bac', '2806:2f0:a7e1:fe5b:2d6a:3d0d:7f0b:7560', '200.68.173.212', '200.68.173.156', '189.203.89.37', '2806:2f0:a7e1:fe5b:75bb:ebe8:f4a1:7c87', '2806:2f0:a7e1:fe5b:9003:be11:6851:de1f', '200.68.173.220', '200.68.159.130', '2806:2f0:a7e1:fe5b:3dad:659e:88fc:7120', '2806:2f0:a7e1:fe5b:58c4:b247:76fa:bd9c', '2806:2f0:a7e1:fe5b:985d:285b:36c2:b231', '200.68.173.114', '200.68.173.180', '2806:2f0:a7e1:fe5b:547f:2d4:f673:9b01', '2806:2f0:a7e1:fe5b:4a:a563:ea84:e06d', '200.68.173.19', '165.225.218.166', '136.226.112.179', '200.68.183.17', '170.85.67.34', '200.68.183.188', '187.190.147.55', '200.68.183.12', '200.68.183.167', '2806:2f0:a7e1:fe5b:7819:809b:238:faf2', '170.85.66.251', '170.85.67.5', '189.203.45.165', '200.68.159.11', '2806:2f0:a7e1:fe5b:7ced:6fb:d3ea:b611', '2806:2f0:a7e1:fe5b:ad7c:2af1:1227:8d84', '2806:2f0:a7e1:fe5b:5d83:9b53:1e73:8678', '200.68.173.61', '2806:2f0:a7e1:fe5b:a14c:2b2f:c05e:2269', '200.68.173.75', '2806:2f0:a7e1:fe5b:a505:8973:509c:4478', '2806:2f0:a7e1:fe5b:8463:3bb2:b612:cd71', '2806:2f0:a7e1:fe5b:c587:4d44:7d53:eda7', '148.241.64.45', '200.68.186.9', '200.68.159.181', '2806:2f0:a7e1:fe5b:bcb1:e879:b7ea:c12b', '148.241.64.27', '200.68.183.5', '2806:2f0:a7e1:fe5b:b940:4138:67fb:b0c7', '2806:2f0:a7e1:fe5b:786e:d0c5:9699:7eef', '200.68.158.34', '200.68.159.153', '2806:2f0:a7e1:fe5b:955:fa09:77a8:94f4', '2806:2f0:a7e1:fe5b:109e:d692:21d2:ded0', '200.68.159.31', '200.68.158.33', '200.68.158.99', '2806:2f0:a7e1:fe5b:a41c:a8fb:2f67:6eb3', '2806:2f0:a7e1:fe5b:b83b:49f1:dfac:ac84', '2806:2f0:a7e1:fe5b:6c9b:f092:b891:b3e9', '200.68.183.39', '200.68.183.191', '2806:2f0:a7e1:fe5b:5c79:3df7:bf22:c808', '187.190.154.125', '2806:2f0:a7e1:fe5b:a505:a416:8206:5381', '200.68.183.52', '2806:2f0:a7e1:fe5b:570:c444:953b:96c8', '2806:2f0:a7e1:fe5b:6de3:1676:3b64:cd7e', '200.68.173.141', '200.68.158.22', '200.68.183.50', '200.68.183.173', '200.68.158.98', '2806:2f0:a7e1:fe5b:e05b:fdef:387d:edf6', '200.68.158.17', '187.188.9.199', '2806:2f0:a7e1:fe5b:7909:645d:b14f:ef54', '200.68.158.65', '187.189.114.194', '2806:2f0:a7e1:fe5b:2c94:26ea:1124:9c41', '2806:2f0:a7e1:fe5b:d86d:de29:9567:8ac5', '170.85.66.164', '148.241.64.24', '200.68.159.182', '2806:2f0:a7e1:fe5b:88b1:57da:3231:ba94', '200.68.183.130', '200.68.183.29', '200.68.183.129', '148.241.64.63', '200.68.183.7', '200.68.183.186', '200.68.173.84', '200.68.159.46', '148.241.64.69', '148.241.64.75', '200.68.159.176', '2806:2f0:a7e1:fe5b:7c0a:86ef:eda4:288e', '2806:2f0:a7e1:fe5b:9d93:c0c:2318:5598', '148.241.64.72', '2806:2f0:a7e1:fe5b:dd34:5e0a:ff32:fb72', '2806:2f0:a7e1:fe5b:d8b6:3040:6cf1:7ce9', '136.226.112.164', '170.85.66.178', '200.68.183.144', '2806:2f0:a7e1:fe5b:f8d8:5b3e:be9f:4790', '200.68.183.44', '2806:2f0:a7e1:fe5b:a9a5:4fe1:639:c4c', '2806:2f0:a7e1:fe5b:8989:14f0:f371:914f', '2806:2f0:a7e1:fe5b:6497:47d7:ebb2:da16', '200.68.183.57', '2806:2f0:a7e1:fe5b:4c6b:974:ef12:e173', '2806:2f0:a7e1:fe5b:1887:d2e4:abb5:7e6d', '187.189.221.2', '200.68.183.134', '200.68.183.37', '2806:2f0:a7e1:fe5b:a5d6:5671:9044:c070', '148.241.64.9', '200.68.159.129', '2806:2f0:a7e1:fe5b:88da:8a8f:be95:cac9', '200.68.158.12', '200.68.173.150', '200.68.159.40', '2806:2f0:a7e1:fe5b:484b:894c:e8a8:242d', '2806:2f0:a7e1:fe5b:795d:3a66:2490:39c1', '2806:2f0:a7e1:fe5b:e131:6245:66a1:7c25', '189.203.29.134', '200.68.183.38', '200.68.183.183', '2806:2f0:a7e1:fe5b:e092:8031:40b3:b46', '2806:2f0:a7e1:fe5b:99e2:1772:1d17:15f2', '2806:2f0:a7e1:fe5b:9c40:597b:cf7f:e6c5', '2806:2f0:a7e1:fe5b:5cf5:46cd:e34b:c19d', '2806:2f0:a7e1:fe5b:71d2:3333:a588:e9c5', '2806:2f0:a7e1:fe5b:e999:7abb:eaa5:260f', '200.68.173.218', '200.68.173.235', '200.68.173.4', '2806:2f0:a7e1:fe5b:348b:9940:8131:b65e', '2806:2f0:a7e1:fe5b:6498:5beb:3143:8315', '2806:2f0:a7e1:fe5b:65fc:1ce5:d979:5aef', '200.68.158.110', '2806:2f0:a7e1:fe5b:3070:ff57:545:12b5', '2806:2f0:a7e1:fe5b:7428:6610:9213:de5', '2806:2f0:a7e1:fe5b:d82d:e960:4485:8506', '148.241.64.33', '2806:2f0:a7e1:fe5b:a478:c26c:6898:35c4', '200.68.158.77', '2806:2f0:a7e1:fe5b:2472:6c67:9096:aec4', '200.68.158.2', '170.85.66.245', '2806:2f0:a7e1:fe5b:c8aa:5ba7:b6ac:7ca3', '170.85.67.31', '200.68.183.162', '2806:2f0:a7e1:fe5b:c52f:cd71:b3:e1d6', '200.68.159.27', '2806:2f0:a7e1:fe5b:a83b:c374:c49c:c580', '2806:2f0:a7e1:fe5b:f472:29df:8944:8dbe', '200.68.187.89', '200.68.158.29', '2806:2f0:a7e1:fe5b:79d4:1df6:47fb:88f4', '2806:2f0:a7e1:fe5b:fd74:b334:9513:2a4e', '2806:2f0:a7e1:fe5b:5ded:687c:2341:5d8e', '200.68.183.189', '2806:2f0:a7e1:fe5b:8dcd:ff02:7676:e66', '136.226.112.89', '200.68.183.150', '200.68.183.4', '2806:2f0:a7e1:fe5b:2de6:a8d:d410:bb32', '2806:2f0:a7e1:fe5b:2d09:c7c6:c38a:3eb6', '2806:2f0:a7e1:fe5b:6d30:d238:d03f:fa5d', '200.68.183.147', '2806:2f0:a7e1:fe5b:1ce9:e6e6:af4a:4b99', '2806:2f0:a7e1:fe5b:c74:96ff:3f1:e4d6', '2806:2f0:a7e1:fe5b:55fe:6a73:6af1:dfec', '200.68.158.106', '200.68.159.158', '2806:2f0:a7e1:fe5b:51e4:b622:b789:ee1c', '187.190.185.109', '200.68.158.16', '200.68.173.234', '148.241.64.78', '200.68.173.135', '200.68.173.125', '2806:2f0:a7e1:f98e:a0a0:a1da:3db6:f91c', '200.68.158.51', '2806:2f0:a7e1:f98e:e1d3:7b1a:4760:e0ff', '2806:2f0:a7e1:f98e:1804:7992:f131:292', '200.68.183.13', '165.225.218.139', '200.68.183.149', '2806:2f0:a7e1:f98e:8d92:eb0a:989d:36b9', '200.68.183.159', '200.68.158.8', '200.68.159.167', '2806:2f0:a7e1:f98e:2c37:39ac:41d9:26d6', '2806:2f0:a7e1:f98e:40e8:2e2:8674:db1c', '2806:2f0:a7e1:f98e:cc90:9462:7e:c4ce', '2806:2f0:a7e1:f98e:b942:63aa:8841:5f8d', '2806:2f0:a7e1:f98e:a929:e12c:a384:cbd3', '200.68.158.66', '2806:2f0:a7e1:f98e:615e:596:6141:1ef5', '200.68.158.1', '2806:2f0:a7e1:f98e:d118:863c:da70:f9bf', '200.68.158.55', '2806:2f0:a7e1:f98e:786c:5a53:d16b:f420', '200.68.158.5', '200.68.159.171', '200.68.158.14', '2806:2f0:a7e1:f98e:154e:b161:d95c:5ee6', '2806:2f0:a7e1:f98e:d50:add1:738a:5154', '2806:2f0:a7e1:f98e:9c30:b842:8e96:b16f', '2806:2f0:a7e1:f98e:e9cc:48d7:5fc9:2844', '170.85.66.172', '2806:2f0:a7e1:f98e:4d27:99bf:18e3:d1d0', '2806:2f0:a7e1:f98e:dcdf:5a32:6fe9:dce', '2806:2f0:a7e1:f98e:2424:5b5c:7117:7926', '2806:2f0:a7e1:f98e:78c2:84:eb8b:9d3d', '2806:2f0:a7e1:f98e:cdad:8a0e:5ac0:d377', '2806:2f0:a7e1:f98e:8d9e:4a6d:84d5:bf31', '2806:2f0:a7e1:f98e:6190:8d81:5cd:dd2', '2806:2f0:a7e1:f98e:8051:180:8d61:52db', '2806:2f0:a7e1:f98e::5', '165.225.218.141', '170.85.66.199', '2806:2f0:a7e1:f98e:c863:b3e8:ec63:f935', '2806:2f0:a7e1:f98e:f1d0:b98b:a0cc:aae2', '2806:2f0:a7e1:f98e:1150:d7f7:40fa:c8e1', '2806:2f0:a7e1:f98e:ac74:ddff:5ce8:1594', '136.226.0.177', '2806:2f0:a7e1:f98e:d534:9b78:947a:1430', '2806:2f0:a7e1:f98e:74e9:bcb:7f7f:1199', '2806:2a0:b14:9123:6425:1e95:1b05:b389', '2806:2f0:a7e1:f98e:f045:b4de:291:2f01', '2806:2f0:a7e1:f98e:d0e4:d7cb:9b6e:28af', '187.190.254.210', '2806:2f0:a7e1:f98e:c440:7ef:cf8e:b317', '2806:2f0:a7e1:f98e:c596:a46e:16af:4cfc', '2806:2f0:a7e1:f98e:9d66:ca6e:d8af:1865', '2806:2f0:a7e1:f98e:b446:cf0c:97fa:ad41', '136.226.0.165', '2806:2f0:a7e1:f98e:ed64:7281:675b:d4d9', '2806:2f0:a7e1:f98e:9daa:824a:e4c:e6a1', '136.226.0.185', '189.196.20.150', '187.190.194.244', '200.68.173.94', '200.68.173.78', '2806:2f0:a7e1:f98e:4d05:8822:29f8:f2e3', '2806:2f0:a7e1:f98e:d995:cec7:6356:59bc', '170.85.67.11', '187.191.16.123', '2806:2f0:a7e1:f98e:f5e6:8853:f444:43d2', '187.189.127.89', '2806:2f0:a7e1:f98e:b8d1:a13b:b8d6:9dc0', '2806:2f0:a7e1:f98e:dd4b:fd23:3552:8720', '2806:2f0:a7e1:f98e:35aa:be09:afa3:b4c1', '136.226.112.189', '2806:2f0:a7e1:f98e:cc3d:8fe7:b8c:60d7', '2806:2f0:a7e1:f98e:6d63:c834:863a:27ea', '170.85.66.207', '2806:2f0:a7e0:ec01:85c4:5479:1f02:90f8', '2806:2f0:a7e1:f98e:4d75:f11:ce4d:4a55', '2806:2f0:a7e0:ec01:18d9:1e47:df86:af31', '2806:2f0:a7e0:ec01:b8d2:5915:8da1:7b87', '2806:2f0:a7e0:ec01:64a4:1a8e:731f:b8bc', '2806:2f0:a7e0:ec01:354a:a201:1d54:43b2', '170.85.66.166', '136.226.0.195', '2806:2f0:a7e0:ec01:2db6:1dbe:a349:32d9', '2806:2f0:a7e0:ec01:9853:502e:be7a:b417', '170.85.66.248', '2806:2f0:a7e0:ec01:f500:4023:fab7:a946', '2806:2f0:a7e0:ec01:4130:50ca:d048:a5e7', '2806:2f0:a7e0:ec01:71e1:3cde:b757:7e4', '136.226.0.191', '2806:2f0:a7e0:ec01:5424:1c9c:d1cf:4e18', '170.85.66.179', '2806:2f0:a7e1:f801:9de2:de08:fe17:2150', '2806:2f0:a7e1:f801:b118:42b1:38dc:58be', '136.226.112.107', '2806:2f0:a7e1:f801:8817:8ff:ae0d:2959', '2806:2f0:a7e1:f801:dd60:a43b:8715:71f7', '2806:2f0:a7e1:f801:1def:38fa:eab0:90b2', '201.147.97.34', '2806:2f0:a7e1:f801:75d6:c7cb:f9c7:a30b', '201.141.8.0', '2806:2f0:a7e1:f801:9c7f:1ac5:243d:2cc7', '2806:2f0:a7e1:f801:ad94:5a30:d475:1a11', '2806:2f0:a7e1:f801:4cca:c8b2:7f22:c485', '200.68.159.143', '2806:2f0:a7e1:f801:133:3076:86c:1809', '170.85.66.188', '2806:2f0:a7e1:f801:f160:c791:fe65:52e', '136.226.112.200', '136.226.64.207', '2806:2f0:a7e0:ec01:97d:b271:8ee6:68a', '170.85.66.202', '2806:2f0:a7e0:ec01:992d:3088:f1c4:537e', '2806:2f0:a7e0:ec01:c957:e6fa:bd20:b719', '2806:2f0:a7e0:ec01:ad25:1779:ac38:ab95', '136.226.0.193', '2806:2f0:a7e0:ec01:601e:7107:265a:7725', '2806:2f0:a7e0:ec01:d0f7:1ae6:fe84:1aa6', '2806:2f0:a7e0:ec01:7c7a:dc86:64b5:72f2', '2806:2f0:a7e0:ec01:15c8:edca:4a89:d961', '2806:2f0:a7e0:ec01:24ff:b108:623f:d535', '170.85.66.185', '2806:2f0:a7e0:ec01:886d:63fc:30c4:3885', '2806:2f0:a7e0:ec01:8c07:9b9:da24:6e4f', '187.190.203.89', '170.85.66.209', '2806:2f0:a7e0:ec01:3d61:6c2:6047:7617', '136.226.0.187', '2806:2f0:a7e0:ec01:2d0e:f009:263a:e47d', '200.68.158.108', '2806:2f0:a7e1:f401:799b:d49e:9ec7:198', '2806:2f0:a7e1:f401:f9b5:557a:5457:72cd', '2806:2f0:a7e1:f401:fd6c:5280:996a:2fe2', '165.225.218.168', '2806:2f0:a7e1:f401:c161:64ee:929f:ac5f', '2806:2f0:a7e1:f401:ec71:46ab:e654:241c', '2806:2f0:a7e1:f401:c133:4ce4:9ce:1f2c', '2806:2f0:a7e1:f401:34df:e015:aeb5:ce4', '2806:2f0:a7e1:f401:2857:62b6:f0fc:3bc0', '2806:2f0:a7e1:f401:80dd:65f:622:5bc1', '2806:2f0:a7e1:f401:40e9:d34d:b53b:b8d8', '136.226.112.119', '2806:2f0:a7e1:f401:253f:ef3d:42e4:5ad0', '165.225.218.148', '2806:2f0:a7e1:f401:d0e3:8845:4253:8b8b', '2806:2f0:a7e1:f401:e005:d06b:3499:f16d', '2806:2f0:a7e1:f401:641a:d810:4b24:d89a', '187.190.185.142', '2806:2f0:a7e1:f401::7', '2806:2f0:a7e1:f401:c043:1f83:26c1:4b80', '2806:2f0:a7e1:f401:d42:13b5:ba9c:d06e', '189.236.119.76', '2806:2f0:a7e1:f401:3929:6532:b12e:db2d', '2806:2a0:135:bff2:6d6f:8b91:db22:ad08', '2806:2f0:a7e1:f401:780d:5f4d:eeb9:e5df', '2806:2f0:a7e1:f401:d8e8:f177:e398:1e60', '2806:2f0:a7e1:f401:d445:cd2a:4659:e585', '136.226.112.94', '2806:2f0:a7e1:f401:5556:2513:2d10:903a', '2806:2f0:a7e1:f401:78a1:c45f:39fd:cd8e', '2806:2f0:a7e1:f401:d118:ba5:c71d:a6b1', '2806:2f0:a7e1:f401:1917:82f:606e:26c6', '187.190.229.178', '2806:2f0:a7e1:f401:f13e:f66a:6b9a:a02', '2806:2f0:a7e1:f401:7cdf:8e18:dbf7:a910', '2806:2f0:a7e1:f401:8cb5:4844:41b0:cf46', '2806:2f0:a7e1:f401:5031:1859:43d7:d6ab', '201.141.8.93', '189.146.218.190', '187.170.125.78', '201.103.149.179', '189.235.164.243', '201.103.11.112', '201.103.226.39', '2806:2f0:a7e1:f401:e83b:19e4:13cc:8521', '2806:2f0:a7e1:f401:85b3:8bd:8a20:4b29', '136.226.112.203', '2806:2f0:a7e1:f401:551b:3057:fdb4:3d2f', '187.230.186.182', '170.85.66.169', '136.226.112.120', '2806:2f0:a7e1:f401:d856:2d51:577c:28ed', '2806:2f0:a7e1:f401:3435:3db9:574:62eb', '2806:2f0:a7e1:f401:4599:3ba9:64c4:ac2', '187.131.158.177', '2806:2f0:a7e1:f401:1567:c004:24d9:beaa', '2806:2f0:a7e1:f401:1935:2c67:59c0:e955', '170.85.66.208', '187.188.227.177', '2806:2f0:a7e1:f401:7c43:562b:bfae:ae88', '2806:2f0:a7e1:f401:7013:efc3:3b9f:ccee', '189.202.184.40', '189.202.184.39', '2806:2f0:a7e1:f401:180e:5e2d:728:2751', '165.225.218.161', '136.226.112.81', '148.241.64.48', '2806:2f0:a7e1:f401:7930:7163:df43:1276', '2806:2f0:a7e1:f401:f174:9328:3a21:4426', '136.226.112.103', '2806:2f0:a7e1:f401:d123:2f30:52c8:27e2', '2806:2f0:a7e1:f401:9816:d98e:3bba:5294', '2806:2f0:a7e1:f401:4028:f010:3854:648e', '2806:2f0:a7e1:f401:14c1:90aa:4886:f1ee', '136.226.0.166', '2806:2f0:a7e1:f401:8932:519d:b8a1:de30', '2806:2f0:a7e1:f401:2c11:6574:697b:52cf', '187.188.10.241', '2806:2f0:a7e1:f401:b068:7d7f:b700:70ef', '2806:2f0:a7e1:f401:d89b:2f9b:3148:3dfd', '2806:2f0:a7e1:f401:38cd:5456:67a7:eaf3', '2806:2f0:a7e1:f401:715f:c403:fc53:7922', '2806:2f0:a7e1:f401:8ced:349d:38f7:13aa', '2806:2f0:a7e1:f401:bdd1:16b6:ba4:cb37', '2806:2f0:a7e1:f401:2cac:694d:322:de0', '2806:2f0:a7e1:f401:7c56:2970:b07e:b13a', '2806:2f0:a7e1:f401:ddb:dee:ee81:9834', '165.225.218.162', '2806:2f0:a7e1:f401:7cdf:ccfd:8869:94b2', '2806:2f0:a7e1:f401:c72:2bd2:9152:992a', '2806:2f0:a7e1:f401:a5a8:9d1:fad:d454', '2806:2f0:a7e1:f401:b0ed:cc6f:6cbf:6171', '2806:2a0:105:348:b44c:4655:8f23:db26', '200.68.173.110', '2806:2f0:a7e1:f401:5445:32fb:28bc:23a3', '2806:2f0:a7e1:f401:d06e:c752:aa17:db16', '2806:2f0:a7e1:f401:21e0:dd6c:f55b:101b', '170.85.66.255', '136.226.0.182', '2806:2f0:a7e1:f401:c831:fe59:df89:52a', '148.241.64.96']
Cantidad de unicos:  604

Valores unicos de  master_metadata_track_name

### Frequency encoding y label encoding para artistas

In [11]:
diccionario_frecuencias = df['master_metadata_album_artist_name'].value_counts().to_dict()

artistas_unicos = df['master_metadata_album_artist_name'].dropna().unique()
diccionario_ids = {artista: idx for idx, artista in enumerate(artistas_unicos)}

df['artist_frequency'] = df['master_metadata_album_artist_name'].map(diccionario_frecuencias)
df['artist_id'] = df['master_metadata_album_artist_name'].map(diccionario_ids)

df.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode,day_of_week,hour,artist_frequency,artist_id
0,2025-12-16 20:30:15-06:00,windows,238423,MX,2806:2f0:a7e1:fe5b:e80b:6db9:a0d7:912a,Jenga (Cuando Te Dejaba Ganar),Procrastinación 1 Yo 0,Caídas y Vueltas,spotify:track:5BLRVVXNBbOfepvtTBi75t,trackdone,logout,True,False,False,1765938376,0.0,1,20,54,0
1,2026-01-01 06:46:23-06:00,ios,82327,MX,189.203.193.241,Do Nothin' Till You Hear From Me - 1956 Version,Billie Holiday,Ben Webster's Finest Hour,spotify:track:1UJJ2S9LLjOdSRV5GcKsZe,trackdone,unexpected-exit-while-paused,False,False,False,1767221154,0.0,3,6,27,1
2,2026-01-02 12:24:41-06:00,windows,192467,MX,136.226.112.100,slow,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:4aaiI9YCt4KucUsMmLfGOx,fwdbtn,trackdone,False,False,False,1767378088,0.0,4,12,108,2
3,2026-01-02 12:28:18-06:00,windows,217573,MX,136.226.112.100,thorn,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:4JX851uapk8BbbZ6ZkNIHn,trackdone,trackdone,False,False,False,1767378279,0.0,4,12,108,2
4,2026-01-02 12:31:48-06:00,windows,210360,MX,136.226.112.100,cigarette in your bed,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:7cQcEUO7KLVciSS5LqzoyZ,trackdone,trackdone,False,False,False,1767378497,0.0,4,12,108,2

In [12]:
# guardando el diccionario de frecuencias y labels
with open('../data/mapeo_artistas.json', 'w', encoding='utf-8') as f:
    json.dump(diccionario_ids, f, ensure_ascii=False, indent=4)

In [13]:
columnas_texto = [
    'master_metadata_album_artist_name', 
    'master_metadata_track_name', 
    'master_metadata_album_album_name'
]
df = df.drop(columns=columnas_texto)

df.head()

,ts,platform,ms_played,conn_country,ip_addr,spotify_track_uri,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode,day_of_week,hour,artist_frequency,artist_id
0,2025-12-16 20:30:15-06:00,windows,238423,MX,2806:2f0:a7e1:fe5b:e80b:6db9:a0d7:912a,spotify:track:5BLRVVXNBbOfepvtTBi75t,trackdone,logout,True,False,False,1765938376,0.0,1,20,54,0
1,2026-01-01 06:46:23-06:00,ios,82327,MX,189.203.193.241,spotify:track:1UJJ2S9LLjOdSRV5GcKsZe,trackdone,unexpected-exit-while-paused,False,False,False,1767221154,0.0,3,6,27,1
2,2026-01-02 12:24:41-06:00,windows,192467,MX,136.226.112.100,spotify:track:4aaiI9YCt4KucUsMmLfGOx,fwdbtn,trackdone,False,False,False,1767378088,0.0,4,12,108,2
3,2026-01-02 12:28:18-06:00,windows,217573,MX,136.226.112.100,spotify:track:4JX851uapk8BbbZ6ZkNIHn,trackdone,trackdone,False,False,False,1767378279,0.0,4,12,108,2
4,2026-01-02 12:31:48-06:00,windows,210360,MX,136.226.112.100,spotify:track:7cQcEUO7KLVciSS5LqzoyZ,trackdone,trackdone,False,False,False,1767378497,0.0,4,12,108,2

### One hot encoding
**Aplicado a platform, reason_start, reason_end, y conn_country**
Dado que estas variables tienen baja cardinalidad y nos ayuda a entnder mejor los compportamientos de reproducción

In [14]:
columnas_baja_cardinalidad = [
    'platform', 
    'reason_start', 
    'reason_end', 
    'conn_country'
    ]

df = pd.get_dummies(df, columns=columnas_baja_cardinalidad, dtype=int)

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10589 entries, 0 to 10588
Data columns (total 37 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   ts                                       10589 non-null  datetime64[ns, America/Mexico_City]
 1   ms_played                                10589 non-null  int64
 2   ip_addr                                  10589 non-null  object
 3   spotify_track_uri                        10589 non-null  object
 4   shuffle                                  10589 non-null  bool
 5   skipped                                  10589 non-null  bool
 6   offline                                  10589 non-null  bool
 7   offline_timestamp                        10589 non-null  int64
 8   incognito_mode                           10586 non-null  float64
 9   day_of_week                              10589 non-null  int32
 10  hour                                     10589 non-null  int32
 11  artist_frequency                         10589 non-null  int64
 12  artist_id                                10589 non-null  int64
 13  platform_ios                             10589 non-null  int64
 14  platform_osx                             10589 non-null  int64
 15  platform_unknown                         10589 non-null  int64
 16  platform_windows                         10589 non-null  int64
 17  reason_start_appload                     10589 non-null  int64
 18  reason_start_backbtn                     10589 non-null  int64
 19  reason_start_clickrow                    10589 non-null  int64
 20  reason_start_fwdbtn                      10589 non-null  int64
 21  reason_start_playbtn                     10589 non-null  int64
 22  reason_start_remote                      10589 non-null  int64
 23  reason_start_trackdone                   10589 non-null  int64
 24  reason_start_trackerror                  10589 non-null  int64
 25  reason_start_unknown                     10589 non-null  int64
 26  reason_end_backbtn                       10589 non-null  int64
 27  reason_end_endplay                       10589 non-null  int64
 28  reason_end_fwdbtn                        10589 non-null  int64
 29  reason_end_logout                        10589 non-null  int64
 30  reason_end_remote                        10589 non-null  int64
 31  reason_end_trackdone                     10589 non-null  int64
 32  reason_end_trackerror                    10589 non-null  int64
 33  reason_end_unexpected-exit               10589 non-null  int64
 34  reason_end_unexpected-exit-while-paused  10589 non-null  int64
 35  conn_country_MX                          10589 non-null  int64
 36  conn_country_US                          10589 non-null  int64
dtypes: bool(3), datetime64[ns, America/Mexico_City](1), float64(1), int32(2), int64(28), object(2)
memory usage: 2.7+ MB

,ts,ms_played,ip_addr,spotify_track_uri,shuffle,skipped,offline,offline_timestamp,incognito_mode,day_of_week,...,reason_end_endplay,reason_end_fwdbtn,reason_end_logout,reason_end_remote,reason_end_trackdone,reason_end_trackerror,reason_end_unexpected-exit,reason_end_unexpected-exit-while-paused,conn_country_MX,conn_country_US
0,2025-12-16 20:30:15-06:00,238423,2806:2f0:a7e1:fe5b:e80b:6db9:a0d7:912a,spotify:track:5BLRVVXNBbOfepvtTBi75t,True,False,False,1765938376,0.0,1,...,0,0,1,0,0,0,0,0,1,0
1,2026-01-01 06:46:23-06:00,82327,189.203.193.241,spotify:track:1UJJ2S9LLjOdSRV5GcKsZe,False,False,False,1767221154,0.0,3,...,0,0,0,0,0,0,0,1,1,0
2,2026-01-02 12:24:41-06:00,192467,136.226.112.100,spotify:track:4aaiI9YCt4KucUsMmLfGOx,False,False,False,1767378088,0.0,4,...,0,0,0,0,1,0,0,0,1,0
3,2026-01-02 12:28:18-06:00,217573,136.226.112.100,spotify:track:4JX851uapk8BbbZ6ZkNIHn,False,False,False,1767378279,0.0,4,...,0,0,0,0,1,0,0,0,1,0
4,2026-01-02 12:31:48-06:00,210360,136.226.112.100,spotify:track:7cQcEUO7KLVciSS5LqzoyZ,False,False,False,1767378497,0.0,4,...,0,0,0,0,1,0,0,0,1,0

### Limpieza final de colunas que no aportan

In [15]:
# 1. Descartar variables no matemáticas o redundantes
columnas_basura = [
    'ts', 
    'ip_addr', 
    'spotify_track_uri', 
    'offline_timestamp'
    ]

df = df.drop(columns=columnas_basura)

#transformando bools an int
df['incognito_mode'] = df['incognito_mode'].fillna(0).astype(int)
columnas_bool = ['shuffle', 'skipped', 'offline']
df[columnas_bool] = df[columnas_bool].astype(int)

columnas = [col for col in df.columns if col != 'skipped'] + ['skipped']
df = df[columnas]

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10589 entries, 0 to 10588
Data columns (total 33 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   ms_played                                10589 non-null  int64
 1   shuffle                                  10589 non-null  int64
 2   offline                                  10589 non-null  int64
 3   incognito_mode                           10589 non-null  int64
 4   day_of_week                              10589 non-null  int32
 5   hour                                     10589 non-null  int32
 6   artist_frequency                         10589 non-null  int64
 7   artist_id                                10589 non-null  int64
 8   platform_ios                             10589 non-null  int64
 9   platform_osx                             10589 non-null  int64
 10  platform_unknown                         10589 non-null  int64
 11  platform_windows                         10589 non-null  int64
 12  reason_start_appload                     10589 non-null  int64
 13  reason_start_backbtn                     10589 non-null  int64
 14  reason_start_clickrow                    10589 non-null  int64
 15  reason_start_fwdbtn                      10589 non-null  int64
 16  reason_start_playbtn                     10589 non-null  int64
 17  reason_start_remote                      10589 non-null  int64
 18  reason_start_trackdone                   10589 non-null  int64
 19  reason_start_trackerror                  10589 non-null  int64
 20  reason_start_unknown                     10589 non-null  int64
 21  reason_end_backbtn                       10589 non-null  int64
 22  reason_end_endplay                       10589 non-null  int64
 23  reason_end_fwdbtn                        10589 non-null  int64
 24  reason_end_logout                        10589 non-null  int64
 25  reason_end_remote                        10589 non-null  int64
 26  reason_end_trackdone                     10589 non-null  int64
 27  reason_end_trackerror                    10589 non-null  int64
 28  reason_end_unexpected-exit               10589 non-null  int64
 29  reason_end_unexpected-exit-while-paused  10589 non-null  int64
 30  conn_country_MX                          10589 non-null  int64
 31  conn_country_US                          10589 non-null  int64
 32  skipped                                  10589 non-null  int64
dtypes: int32(2), int64(31)
memory usage: 2.6 MB

## ydata profilling section

In [16]:
%pip install -U ydata-profiling

Requirement already satisfied: ydata-profiling in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (2.13.5)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (2.1.1)
Requirement already satisfied: minify-html>=0.15.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (2.34.2)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from imagehash==4.3.2->ydata-profiling) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2024.1)
Requirement already satisfied: joblib>=0.14.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.46.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: colorama in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Requirement already satisfied: puremagic in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
%pip install ipywidgets

Requirement already satisfied: ipywidgets in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (8.1.9)
Requirement already satisfied: comm>=0.1.3 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipywidgets) (9.16.1)
Requirement already satisfied: traitlets>=4.3.1 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipywidgets) (5.16.1)
Requirement already satisfied: widgetsnbextension~=4.0.16 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipywidgets) (4.0.16)
Requirement already satisfied: jupyterlab_widgets~=3.0.17 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipywidgets) (3.0.17)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.53)
Requirement already satisfied: psutil>=7 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.7)
Requirement already satisfied: executing>=1.2.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.2)
Requirement already satisfied: pure-eval in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [18]:
import ydata_profiling as pp
pp.ProfileReport(df)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_12224\2977676246.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  import ydata_profiling as pp

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 33/33 [00:00<00:00, 121.03it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [19]:
correlaciones = df.corr()['skipped'].abs().sort_values(ascending=False)

print("Correlación de las variables con 'skipped':")
print(correlaciones)

Correlación de las variables con 'skipped':
skipped                                    1.000000
reason_end_trackdone                       0.850034
reason_end_endplay                         0.839248
ms_played                                  0.565621
reason_end_fwdbtn                          0.428262
reason_start_trackdone                     0.406518
reason_start_clickrow                      0.301602
reason_start_fwdbtn                        0.230422
reason_end_backbtn                         0.178289
platform_ios                               0.101703
platform_osx                               0.096042
reason_end_unexpected-exit-while-paused    0.089850
artist_frequency                           0.078193
reason_start_appload                       0.072395
reason_start_backbtn                       0.065990
reason_start_unknown                       0.056066
day_of_week                                0.050766
reason_end_remote                          0.048183
platform_unknown                           0.040763
reason_end_logout                          0.040547
reason_start_remote                        0.030701
shuffle                                    0.030120
hour                                       0.029222
platform_windows                           0.028804
artist_id                                  0.028561
reason_start_playbtn                       0.027072
incognito_mode                             0.025679
reason_end_trackerror                      0.017352
reason_end_unexpected-exit                 0.016720
offline                                    0.001889
reason_start_trackerror                    0.001426
conn_country_MX                            0.000407
conn_country_US                            0.000407
Name: skipped, dtype: float64

In [20]:
reporte = pp.ProfileReport(df, title="EDA Historial Spotify")
# Exportamos a JSON en lugar de HTML
reporte.to_file("../docs/reporte_exploratorio.json")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 33/33 [00:00<00:00, 150.36it/s]
c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\ydata_profiling\model\pandas\discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 4 6 ... 1 1 1]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(
c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\ydata_profiling\model\pandas\discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[8 2 5 ... 6 6 6]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(

Render JSON:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

## Analisis a posible variable objetivo
**H_0:** Mi variable objetivo será predecir si una canción será saltada ("skipped") basándome en el día de la semana, la hora del día (derivados de "ts") y la plataforma ("platform").