# EDA para toma de decissión
Aquí definiré la variable objetivo al entender la limpieza de mis datos, la distribución y multiples metricas estadisticas

## Datos

In [1]:
import json
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as datetime

In [2]:
ruta = "../data/Streaming_History_Audio_2026.json"

df = pd.read_json(ruta)
df.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2025-12-17T02:30:15Z,windows,238423,MX,2806:2f0:a7e1:fe5b:e80b:6db9:a0d7:912a,Jenga (Cuando Te Dejaba Ganar),Procrastinación 1 Yo 0,Caídas y Vueltas,spotify:track:5BLRVVXNBbOfepvtTBi75t,NaN,...,NaN,NaN,NaN,trackdone,logout,True,False,False,1765938376,0.0
1,2026-01-01T12:46:23Z,ios,82327,MX,189.203.193.241,Do Nothin' Till You Hear From Me - 1956 Version,Billie Holiday,Ben Webster's Finest Hour,spotify:track:1UJJ2S9LLjOdSRV5GcKsZe,NaN,...,NaN,NaN,NaN,trackdone,unexpected-exit-while-paused,False,False,False,1767221154,0.0
2,2026-01-02T18:24:41Z,windows,192467,MX,136.226.112.100,slow,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:4aaiI9YCt4KucUsMmLfGOx,NaN,...,NaN,NaN,NaN,fwdbtn,trackdone,False,False,False,1767378088,0.0
3,2026-01-02T18:28:18Z,windows,217573,MX,136.226.112.100,thorn,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:4JX851uapk8BbbZ6ZkNIHn,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,1767378279,0.0
4,2026-01-02T18:31:48Z,windows,210360,MX,136.226.112.100,cigarette in your bed,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:7cQcEUO7KLVciSS5LqzoyZ,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,1767378497,0.0

## Inspección estructural

In [3]:
df.shape

(10589, 23)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10589 entries, 0 to 10588
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ts                                 10589 non-null  object
 1   platform                           10589 non-null  object
 2   ms_played                          10589 non-null  int64
 3   conn_country                       10589 non-null  object
 4   ip_addr                            10589 non-null  object
 5   master_metadata_track_name         10589 non-null  object
 6   master_metadata_album_artist_name  10589 non-null  object
 7   master_metadata_album_album_name   10589 non-null  object
 8   spotify_track_uri                  10589 non-null  object
 9   episode_name                       0 non-null      float64
 10  episode_show_name                  0 non-null      float64
 11  spotify_episode_uri                0 non-null      float64
 12  audiobook_title                    0 non-null      float64
 13  audiobook_uri                      0 non-null      float64
 14  audiobook_chapter_uri              0 non-null      float64
 15  audiobook_chapter_title            0 non-null      float64
 16  reason_start                       10589 non-null  object
 17  reason_end                         10589 non-null  object
 18  shuffle                            10589 non-null  bool
 19  skipped                            10589 non-null  bool
 20  offline                            10589 non-null  bool
 21  offline_timestamp                  10589 non-null  int64
 22  incognito_mode                     10586 non-null  float64
dtypes: bool(3), float64(8), int64(2), object(10)
memory usage: 1.6+ MB

Al observar que 'ts' se encuentra en object se transforma a datetime para poder utilizarla

In [8]:
df['ts'] = pd.to_datetime(df['ts'])
print(df.dtypes)

ts                                   datetime64[ns, UTC]
platform                                          object
ms_played                                          int64
conn_country                                      object
ip_addr                                           object
master_metadata_track_name                        object
master_metadata_album_artist_name                 object
master_metadata_album_album_name                  object
spotify_track_uri                                 object
episode_name                                     float64
episode_show_name                                float64
spotify_episode_uri                              float64
audiobook_title                                  float64
audiobook_uri                                    float64
audiobook_chapter_uri                            float64
audiobook_chapter_title                          float64
reason_start                                      object
reason_end                                        object
shuffle                                             bool
skipped                                             bool
offline                                             bool
offline_timestamp                                  int64
incognito_mode                                   float64
dtype: object

se transforman los datos de ts a datos mas entendibles de día y hora

In [9]:
df['day_of_week'] = df['ts'].dt.dayofweek 

df['hour'] = df['ts'].dt.hour

df[['ts', 'day_of_week', 'hour', 'skipped']].head()

                         ts  day_of_week  hour  skipped
0 2025-12-17 02:30:15+00:00            2     2    False
1 2026-01-01 12:46:23+00:00            3    12    False
2 2026-01-02 18:24:41+00:00            4    18    False
3 2026-01-02 18:28:18+00:00            4    18    False
4 2026-01-02 18:31:48+00:00            4    18    False

In [10]:
df.head()

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode,day_of_week,hour
0,2025-12-17 02:30:15+00:00,windows,238423,MX,2806:2f0:a7e1:fe5b:e80b:6db9:a0d7:912a,Jenga (Cuando Te Dejaba Ganar),Procrastinación 1 Yo 0,Caídas y Vueltas,spotify:track:5BLRVVXNBbOfepvtTBi75t,NaN,...,NaN,trackdone,logout,True,False,False,1765938376,0.0,2,2
1,2026-01-01 12:46:23+00:00,ios,82327,MX,189.203.193.241,Do Nothin' Till You Hear From Me - 1956 Version,Billie Holiday,Ben Webster's Finest Hour,spotify:track:1UJJ2S9LLjOdSRV5GcKsZe,NaN,...,NaN,trackdone,unexpected-exit-while-paused,False,False,False,1767221154,0.0,3,12
2,2026-01-02 18:24:41+00:00,windows,192467,MX,136.226.112.100,slow,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:4aaiI9YCt4KucUsMmLfGOx,NaN,...,NaN,fwdbtn,trackdone,False,False,False,1767378088,0.0,4,18
3,2026-01-02 18:28:18+00:00,windows,217573,MX,136.226.112.100,thorn,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:4JX851uapk8BbbZ6ZkNIHn,NaN,...,NaN,trackdone,trackdone,False,False,False,1767378279,0.0,4,18
4,2026-01-02 18:31:48+00:00,windows,210360,MX,136.226.112.100,cigarette in your bed,my bloody valentine,ep’s 1988-1991 and rare tracks,spotify:track:7cQcEUO7KLVciSS5LqzoyZ,NaN,...,NaN,trackdone,trackdone,False,False,False,1767378497,0.0,4,18

In [11]:
df.isnull().sum()

ts                                       0
platform                                 0
ms_played                                0
conn_country                             0
ip_addr                                  0
master_metadata_track_name               0
master_metadata_album_artist_name        0
master_metadata_album_album_name         0
spotify_track_uri                        0
episode_name                         10589
episode_show_name                    10589
spotify_episode_uri                  10589
audiobook_title                      10589
audiobook_uri                        10589
audiobook_chapter_uri                10589
audiobook_chapter_title              10589
reason_start                             0
reason_end                               0
shuffle                                  0
skipped                                  0
offline                                  0
offline_timestamp                        0
incognito_mode                           3
day_of_week                              0
hour                                     0
dtype: int64

al observar variables con muchos nulos hacemos drop

In [12]:
columnas_null = [
    "episode_name", 
    "episode_show_name", 
    "spotify_episode_uri", 
    "audiobook_title", 
    "audiobook_uri", 
    "audiobook_chapter_uri", 
    "audiobook_chapter_title"
]

df = df.drop(columns=columnas_null)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10589 entries, 0 to 10588
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ts                                 10589 non-null  datetime64[ns, UTC]
 1   platform                           10589 non-null  object
 2   ms_played                          10589 non-null  int64
 3   conn_country                       10589 non-null  object
 4   ip_addr                            10589 non-null  object
 5   master_metadata_track_name         10589 non-null  object
 6   master_metadata_album_artist_name  10589 non-null  object
 7   master_metadata_album_album_name   10589 non-null  object
 8   spotify_track_uri                  10589 non-null  object
 9   reason_start                       10589 non-null  object
 10  reason_end                         10589 non-null  object
 11  shuffle                            10589 non-null  bool
 12  skipped                            10589 non-null  bool
 13  offline                            10589 non-null  bool
 14  offline_timestamp                  10589 non-null  int64
 15  incognito_mode                     10586 non-null  float64
 16  day_of_week                        10589 non-null  int32
 17  hour                               10589 non-null  int32
dtypes: bool(3), datetime64[ns, UTC](1), float64(1), int32(2), int64(2), object(9)
memory usage: 1.2+ MB

## ydata profilling section

In [13]:
%pip install -U ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (2.2.3)
Collecting matplotlib<=3.10,>=3.5 (from ydata-profiling)
  Downloading matplotlib-3.10.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting pydantic<3,>=2 (from ydata-profiling)
  Downloading pydantic-2.13.5-py3-none-any.whl.metadata (110 kB)
Collecting PyYAML<6.1,>=6.0.3 (from ydata-profiling)
  Using cached pyyaml-6.0.3-cp312-cp312-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (2.1.1)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-win_amd64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (2.34.2)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ydata-profiling) (0.14.6)
Collecting typeguard<5,>=4 (from ydata-profiling)
  Downloading typeguard-4.6.0-py3-none-any.whl.metadata (3.7 kB)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting wordcloud>=1.9.4 (from ydata-profiling)
  Downloading wordcloud-1.9.6-cp312-cp312-win_amd64.whl.metadata (3.5 kB)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Collecting numba<0.63,>=0.60 (from ydata-profiling)
  Downloading numba-0.62.1-cp312-cp312-win_amd64.whl.metadata (2.9 kB)
Collecting PyWavelets (from imagehash==4.3.2->ydata-profiling)
  Downloading pywavelets-1.9.0-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: pillow in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from imagehash==4.3.2->ydata-profiling) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Collecting llvmlite<0.46,>=0.45.0dev0 (from numba<0.63,>=0.60->ydata-profiling)
  Downloading llvmlite-0.45.1-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: pytz>=2020.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2024.1)
Requirement already satisfied: joblib>=0.14.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=2->ydata-profiling)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.5 (from pydantic<3,>=2->ydata-profiling)
  Downloading pydantic_core-2.46.5-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Collecting typing-inspection>=0.4.2 (from pydantic<3,>=2->ydata-profiling)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: colorama in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Collecting attrs>=19.3.0 (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: networkx>=2.4 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.16.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading matplotlib-3.10.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 8.0/8.0 MB 62.2 MB/s  0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading numba-0.62.1-cp312-cp312-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 2.7/2.7 MB 77.6 MB/s  0:00:00
Downloading llvmlite-0.45.1-cp312-cp312-win_amd64.whl (38.1 MB)
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   ------------ --------------------------- 12.3/38.1 MB 59.4 MB/s eta 0:00:01
   -------------------------------- ------- 30.9/38.1 MB 75.5 MB/s eta 0:00:01
   ---------------------------------------- 38.1/38.1 MB 67.4 MB/s  0:00:00
Downloading phik-0.12.5-cp312-cp312-win_amd64.whl (676 kB)
   ---------------------------------------- 0.0/676.2 kB ? eta -:--:--
   ---------------------------------------- 676.2/676.2 kB 13.4 MB/s  0:00:00
Downloading pydantic-2.13.5-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.5-cp312-cp312-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 57.5 MB/s  0:00:00
Using cached pyyaml-6.0.3-cp312-cp312-win_amd64.whl (154 kB)
Downloading typeguard-4.6.0-py3-none-any.whl (36 kB)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-win_amd64.whl (3.1 MB)
   ---------------------------------------- 0.0/3.1 MB ? eta -:--:--
   ---------------------------------------- 3.1/3.1 MB 62.1 MB/s  0:00:00
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading wordcloud-1.9.6-cp312-cp312-win_amd64.whl (307 kB)
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
Downloading pywavelets-1.9.0-cp312-cp312-win_amd64.whl (4.2 MB)
   ---------------------------------------- 0.0/4.2 MB ? eta -:--:--
   ---------------------------------------- 4.2/4.2 MB 63.7 MB/s  0:00:00
Installing collected packages: minify-html, filetype, typing-inspection, typeguard, PyYAML, PyWavelets, pydantic-core, puremagic, multimethod, llvmlite, dacite, attrs, annotated-types, pydantic, numba, matplotlib, imagehash, wordcloud, visions, phik, ydata-profiling

   ----------------------------------------  0/21 [minify-html]
   - --------------------------------------  1/21 [filetype]
   - --------------------------------------  1/21 [filetype]
   - --------------------------------------  1/21 [filetype]
   - --------------------------------------  1/21 [filetype]
   ----- ----------------------------------  3/21 [typeguard]
   ----- ----------------------------------  3/21 [typeguard]
   ----- ----------------------------------  3/21 [typeguard]
   ------- --------------------------------  4/21 [PyYAML]
   ------- --------------------------------  4/21 [PyYAML]
   ------- --------------------------------  4/21 [PyYAML]
   ------- --------------------------------  4/21 [PyYAML]
   ------- --------------------------------  4/21 [PyYAML]
   --------- ------------------------------  5/21 [PyWavelets]
   --------- ------------------------------  5/21 [PyWavelets]
   --------- ------------------------------  5/21 [PyWavelets]
   --------- ------------------------------  5/21 [PyWavelets]
   --------- ------------------------------  5/21 [PyWavelets]
   --------- ------------------------------  5/21 [PyWavelets]
   --------- ------------------------------  5/21 [PyWavelets]
   --------- ------------------------------  5/21 [PyWavelets]
   --------- ------------------------------  5/21 [PyWavelets]
   --------- ------------------------------  5/21 [PyWavelets]
   --------- ------------------------------  5/21 [PyWavelets]
   ----------- ----------------------------  6/21 [pydantic-core]
   ------------- --------------------------  7/21 [puremagic]
   ------------- --------------------------  7/21 [puremagic]
   ------------- --------------------------  7/21 [puremagic]
   ------------- --------------------------  7/21 [puremagic]
   ------------- --------------------------  7/21 [puremagic]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ----------------- ----------------------  9/21 [llvmlite]
   ------------------- -------------------- 10/21 [dacite]
   ------------------- -------------------- 10/21 [dacite]
   -------------------- ------------------- 11/21 [attrs]
   -------------------- ------------------- 11/21 [attrs]
   -------------------- ------------------- 11/21 [attrs]
   -------------------- ------------------- 11/21 [attrs]
   -------------------- ------------------- 11/21 [attrs]
   -------------------- ------------------- 11/21 [attrs]
   ---------------------- ----------------- 12/21 [annotated-types]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   ------------------------ --------------- 13/21 [pydantic]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]
   -------------------------- ------------- 14/21 [numba]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages\~atplotlib'.
  You can safely remove it manually.

In [15]:
%pip install ipywidgets

Collecting ipywidgets
  Downloading ipywidgets-8.1.9-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: comm>=0.1.3 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipywidgets) (9.16.1)
Requirement already satisfied: traitlets>=4.3.1 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipywidgets) (5.16.1)
Collecting widgetsnbextension~=4.0.16 (from ipywidgets)
  Downloading widgetsnbextension-4.0.16-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.17 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.17-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\Usuario\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.53)
Requirement already satisfied: psutil>=7 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.7)
Requirement already satisfied: executing>=1.2.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.2)
Requirement already satisfied: pure-eval in C:\Users\Usuario\AppData\Roaming\Python\Python312\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Downloading ipywidgets-8.1.9-py3-none-any.whl (140 kB)
Downloading jupyterlab_widgets-3.0.17-py3-none-any.whl (217 kB)
Downloading widgetsnbextension-4.0.16-py3-none-any.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 2.2/2.2 MB 41.8 MB/s  0:00:00
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets

   ------------- -------------------------- 1/3 [jupyterlab_widgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   ---------------------------------------- 3/3 [ipywidgets]

Successfully installed ipywidgets-8.1.9 jupyterlab_widgets-3.0.17 widgetsnbextension-4.0.16
Note: you may need to restart the kernel to use updated packages.

In [16]:
import ydata_profiling as pp
pp.ProfileReport(df)

100%|██████████| 18/18 [00:00<00:00, 42.71it/s]<00:01, 10.52it/s, Describe variable: hour]
Summarize dataset: 100%|██████████| 43/43 [00:03<00:00, 13.30it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:05<00:00,  5.17s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.34s/it]

## Analisis a posible variable objetivo
**H_0:** Mi variable objetivo será predecir si una canción será saltada ("skipped") basándome en el día de la semana, la hora del día (derivados de "ts") y la plataforma ("platform").